# Copyright 2026 Salesforce, Inc. All rights reserved.
# Modifications Copyright (c) 2026 msaleme. Licensed under the MIT License.
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8081
  services:
    upstream:
      address: http://backend
      routes:
        - config:
            destinationPath: /anything/echo/
  policies:
    - policyRef:
        name: approval-execution-binding-v1-0-impl # This value will be overriden during 'make run' execution
      config:
        approvalSource: header
        approvalHeader: x-approval
        approvalRpcField: approvalBinding
        executorHeader: client_id
        requiredPredicates: [P1, P2, P3, P4, P5]
        attesterKeys:
          - kid: approver.example
            key: abv/approver
        clockSkewSeconds: 60
        mode: block
        onDeny: rpc-error
        resultHeader: x-approval-binding
