#!/usr/bin/env python3
# Copyright (c) 2026 msaleme. Licensed under the MIT License.
"""Reject invalid or placeholder Exchange metadata for one policy project.

Checks the source definition (definition/gcl.yaml), the P4A-SUBMISSION.md
applicability line for that policy, and — with --assets — the asset files
generated by `make build` (target/implementation/*, target/wasm32-wasip1/release/*).

Usage: check_exchange_metadata.py <policy-dir> [--assets]
Exits non-zero with one line per problem.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import yaml

EXCHANGE_DESCRIPTION_MAX = 256
MIN_RUNTIME = "1.14.0"
# Asset types this repo has validated each policy against. Declaring anything
# else in gcl.yaml is rejected until it has its own test coverage.
VALIDATED_ASSET_TYPES = {"mcp"}
# How each asset type is named on the P4A-SUBMISSION.md applicability line.
P4A_LABELS = {"mcp": "MCP", "a2a": "A2A", "llm": "LLM"}
PLACEHOLDER = re.compile(r"REPLACE_WITH|TODO|TBD|FIXME|XXX|lorem ipsum|<[A-Z_]+>", re.IGNORECASE)
UUID = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")
NIL_UUID = "00000000-0000-0000-0000-000000000000"


def check_definition(policy: Path, problems: list[str]) -> list[str]:
    gcl = yaml.safe_load((policy / "definition/gcl.yaml").read_text(encoding="utf-8"))
    labels = gcl.get("metadata", {}).get("labels", {})
    for key in ("title", "category", "description"):
        if not str(labels.get(key, "")).strip():
            problems.append(f"gcl.yaml: metadata.labels.{key} is missing or blank")
    description = str(labels.get("description", ""))
    if len(description) > EXCHANGE_DESCRIPTION_MAX:
        problems.append(
            f"gcl.yaml: description is {len(description)} chars, Exchange limit is {EXCHANGE_DESCRIPTION_MAX}"
        )
    for key, value in labels.items():
        if PLACEHOLDER.search(str(value)):
            problems.append(f"gcl.yaml: metadata.labels.{key} contains placeholder text")

    if labels.get("metadata/capabilities/injectionPoint") != "inbound":
        problems.append("gcl.yaml: metadata/capabilities/injectionPoint must be 'inbound'")
    if labels.get("metadata/interfaceScope") != "api,resource":
        problems.append("gcl.yaml: metadata/interfaceScope must be 'api,resource'")
    raw_types = str(labels.get("metadata/capabilities/assetTypes", "")).strip()
    asset_types = [t.strip() for t in raw_types.split(",") if t.strip()]
    if not asset_types:
        problems.append("gcl.yaml: metadata/capabilities/assetTypes is not declared")
    for asset_type in asset_types:
        if asset_type not in VALIDATED_ASSET_TYPES:
            problems.append(f"gcl.yaml: assetType {asset_type!r} has no validated test coverage")

    properties = gcl.get("spec", {}).get("properties", {})
    for name, prop in properties.items():
        if not str(prop.get("description", "")).strip():
            problems.append(f"gcl.yaml: property {name} has no description")
    return asset_types


def check_p4a(policy: Path, asset_types: list[str], problems: list[str]) -> None:
    submission = (policy.parent / "P4A-SUBMISSION.md").read_text(encoding="utf-8")
    marker = f"`/{policy.name}`"
    lines = submission.splitlines()
    try:
        start = next(i for i, line in enumerate(lines) if "Project path:" in line and marker in line)
    except StopIteration:
        problems.append(f"P4A-SUBMISSION.md: no section with Project path {marker}")
        return
    applicability = next(
        (line for line in lines[start : start + 6] if "applicability" in line), None
    )
    if applicability is None:
        problems.append(f"P4A-SUBMISSION.md: {policy.name} section has no applicability line")
        return
    claim = applicability.split("applicability", 1)[1]
    for asset_type, label in P4A_LABELS.items():
        declared = asset_type in asset_types
        claimed = re.search(rf"\b{label}\b", claim) is not None
        if declared and not claimed:
            problems.append(f"P4A-SUBMISSION.md: {policy.name} declares {asset_type} but does not claim {label}")
        if claimed and not declared:
            problems.append(f"P4A-SUBMISSION.md: {policy.name} claims {label} but gcl.yaml does not declare {asset_type}")
    if f"assetTypes: {','.join(asset_types)}" not in applicability:
        problems.append(
            f"P4A-SUBMISSION.md: {policy.name} applicability line must quote assetTypes: {','.join(asset_types)}"
        )


def check_assets(policy: Path, problems: list[str]) -> None:
    cargo_name = None
    impl_asset_id = None
    for line in (policy / "Cargo.toml").read_text(encoding="utf-8").splitlines():
        if line.startswith("name = ") and cargo_name is None:
            cargo_name = line.split("=", 1)[1].strip().strip('"')
        if line.startswith("implementation_asset_id"):
            impl_asset_id = line.split("=", 1)[1].strip().strip('"')

    exchange_path = policy / "target/implementation/exchange.json"
    if not exchange_path.is_file():
        problems.append(f"missing generated asset: {exchange_path}")
        return
    exchange = json.loads(exchange_path.read_text(encoding="utf-8"))
    group_ids = [exchange.get("groupId", "")] + [d.get("groupId", "") for d in exchange.get("dependencies", [])]
    for group_id in group_ids:
        if not UUID.match(group_id) or group_id == NIL_UUID:
            problems.append("exchange.json: groupId is not a real Anypoint organization UUID")
            break
    if exchange.get("assetId") != impl_asset_id:
        problems.append(f"exchange.json: assetId {exchange.get('assetId')!r} != {impl_asset_id!r}")
    if PLACEHOLDER.search(exchange.get("name", "")):
        problems.append("exchange.json: name contains placeholder text")

    for metadata in ("target/implementation/metadata.yaml", "target/implementation-dev/metadata.yaml"):
        path = policy / metadata
        if not path.is_file():
            problems.append(f"missing generated asset: {path}")
            continue
        if f"minRuntimeVersion: {MIN_RUNTIME}" not in path.read_text(encoding="utf-8").splitlines():
            problems.append(f"{metadata}: minRuntimeVersion is not {MIN_RUNTIME}")

    release = policy / "target/wasm32-wasip1/release"
    for name in (f"{cargo_name}.wasm", f"{cargo_name}_definition.yaml", f"{cargo_name}_implementation.yaml"):
        if not (release / name).is_file():
            problems.append(f"missing generated asset: {release / name}")
    definition = release / f"{cargo_name}_definition.yaml"
    if definition.is_file():
        generated = yaml.safe_load(definition.read_text(encoding="utf-8"))
        source = yaml.safe_load((policy / "definition/gcl.yaml").read_text(encoding="utf-8"))
        # The generator adds its own labels (e.g. pdk-cli-version); every source
        # label must survive into the generated definition unchanged.
        generated_labels = generated.get("metadata", {}).get("labels", {})
        for key, value in source.get("metadata", {}).get("labels", {}).items():
            if generated_labels.get(key) != value:
                problems.append(f"generated definition label {key} differs from definition/gcl.yaml")


def main(argv: list[str]) -> int:
    if len(argv) < 2 or len(argv) > 3 or (len(argv) == 3 and argv[2] != "--assets"):
        print(__doc__, file=sys.stderr)
        return 2
    policy = Path(argv[1]).resolve()
    problems: list[str] = []
    asset_types = check_definition(policy, problems)
    check_p4a(policy, asset_types, problems)
    if len(argv) == 3:
        check_assets(policy, problems)
    for problem in problems:
        print(f"{policy.name}: {problem}", file=sys.stderr)
    if not problems:
        print(f"{policy.name}: Exchange metadata OK" + (" (incl. generated assets)" if len(argv) == 3 else ""))
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
